name: Retraining The Model

on:
  schedule:
    - cron: '0 15 * * 0'
  workflow_dispatch:

jobs:
  retraining_model_every_week:
    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v4

      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH
          source $HOME/miniconda/bin/activate
          conda init bash
          source ~/.bashrc

      - name: Create conda environment
        run: |
          conda create --name airquality python=3.8 -y
          source $HOME/miniconda/bin/activate
          conda install -n airquality -c conda-forge prophet pandas altair streamlit numpy -y

      - name: Install additional dependencies
        run: |
          source $HOME/miniconda/bin/activate
          conda activate airquality
          pip install -r requirements.txt

      - name: Run app.py
        run: |
          source $HOME/miniconda/bin/activate
          conda activate airquality
          streamlit run app.py || (echo "Error running app.py" && exit 1)
