name: Update Air Quality Forecast

on:
  schedule:
    - cron: '0 8 * * 0'  # Run at 8:00 AM UTC every Sunday
  workflow_dispatch:  # Manually trigger the workflow

jobs:
    update-forecast:
      runs-on: ubuntu-latest
      
      steps: 
        - uses: actions/checkout@v2
  
        - name: Install Miniconda
          run: |
            wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
            bash miniconda.sh -b -p $HOME/miniconda
            echo "$HOME/miniconda/bin" >> $GITHUB_PATH
            source $HOME/miniconda/bin/activate
            conda init bash
            source ~/.bashrc
  
        - name: Create and activate conda environment
          run: |
            conda create --name airquality -f env.yml
            source $HOME/miniconda/bin/activate
            conda activate airquality
            conda install -n airquality -c conda-forge prophet pandas altair streamlit numpy -y
  
        
        - name: Run data update script
          env:
              GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
          run: |
            source $HOME/miniconda/bin/activate
            conda activate airquality
            python update_forecast.py
  
       